###############################################################################
# Database configuration

# Connection string is in Go pq driver format:
# host=<host> port=<port> user=<databaseUser> password=<databaseUserPassword> dbname=<databaseName>

[database]

connection_string = "host=192.168.0.17 port=5432 user=postgres password=postgres dbname=report_db sslmode=disable"
max_idle_connections = 5
max_open_connections = 20
connection_max_lifetime = "60s"

###############################################################################
# HTTP server configuration

[http]

server_address = ":8080"

read_timeout = "60s"
write_timeout = "60s"

###############################################################################
# Grpc server configuration

[grpc]

user_grpc_connection_string = "user-ms-service:8081"

###############################################################################
# RabbitMQ configuration

[rabbitmq]

connection_string = "amqp://micro:micro@192.168.0.17:5672/"

###############################################################################