apiVersion: v1
kind: Service
metadata:
  name: book-ms-service
spec:
  selector:
    app: book-ms
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: grpc
      protocol: TCP
      port: 8081
      targetPort: 8081