// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usergrpc.proto

package usergrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// AuthorizeUserRequest contains data required for authorize user request
type AuthorizeUserRequest struct {
	AuthorizationToken   string   `protobuf:"bytes,1,opt,name=AuthorizationToken,proto3" json:"AuthorizationToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorizeUserRequest) Reset()         { *m = AuthorizeUserRequest{} }
func (m *AuthorizeUserRequest) String() string { return proto.CompactTextString(m) }
func (*AuthorizeUserRequest) ProtoMessage()    {}
func (*AuthorizeUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b2fcb8862490326, []int{0}
}

func (m *AuthorizeUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizeUserRequest.Unmarshal(m, b)
}
func (m *AuthorizeUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizeUserRequest.Marshal(b, m, deterministic)
}
func (m *AuthorizeUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizeUserRequest.Merge(m, src)
}
func (m *AuthorizeUserRequest) XXX_Size() int {
	return xxx_messageInfo_AuthorizeUserRequest.Size(m)
}
func (m *AuthorizeUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizeUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizeUserRequest proto.InternalMessageInfo

func (m *AuthorizeUserRequest) GetAuthorizationToken() string {
	if m != nil {
		return m.AuthorizationToken
	}
	return ""
}

// AuthorizeUserResponse contains data required for authorize user response
type AuthorizeUserResponse struct {
	UserRole             int64    `protobuf:"varint,1,opt,name=UserRole,proto3" json:"UserRole,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorizeUserResponse) Reset()         { *m = AuthorizeUserResponse{} }
func (m *AuthorizeUserResponse) String() string { return proto.CompactTextString(m) }
func (*AuthorizeUserResponse) ProtoMessage()    {}
func (*AuthorizeUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b2fcb8862490326, []int{1}
}

func (m *AuthorizeUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizeUserResponse.Unmarshal(m, b)
}
func (m *AuthorizeUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizeUserResponse.Marshal(b, m, deterministic)
}
func (m *AuthorizeUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizeUserResponse.Merge(m, src)
}
func (m *AuthorizeUserResponse) XXX_Size() int {
	return xxx_messageInfo_AuthorizeUserResponse.Size(m)
}
func (m *AuthorizeUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizeUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizeUserResponse proto.InternalMessageInfo

func (m *AuthorizeUserResponse) GetUserRole() int64 {
	if m != nil {
		return m.UserRole
	}
	return 0
}

// GetUserIDRequest contains data required for get user ID request
type GetUserIDRequest struct {
	AuthorizationToken   string   `protobuf:"bytes,1,opt,name=AuthorizationToken,proto3" json:"AuthorizationToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserIDRequest) Reset()         { *m = GetUserIDRequest{} }
func (m *GetUserIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserIDRequest) ProtoMessage()    {}
func (*GetUserIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b2fcb8862490326, []int{2}
}

func (m *GetUserIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserIDRequest.Unmarshal(m, b)
}
func (m *GetUserIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserIDRequest.Marshal(b, m, deterministic)
}
func (m *GetUserIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserIDRequest.Merge(m, src)
}
func (m *GetUserIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserIDRequest.Size(m)
}
func (m *GetUserIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserIDRequest proto.InternalMessageInfo

func (m *GetUserIDRequest) GetAuthorizationToken() string {
	if m != nil {
		return m.AuthorizationToken
	}
	return ""
}

// GetUserIDResponse contains data required for get user ID response
type GetUserIDResponse struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserIDResponse) Reset()         { *m = GetUserIDResponse{} }
func (m *GetUserIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserIDResponse) ProtoMessage()    {}
func (*GetUserIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b2fcb8862490326, []int{3}
}

func (m *GetUserIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserIDResponse.Unmarshal(m, b)
}
func (m *GetUserIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserIDResponse.Marshal(b, m, deterministic)
}
func (m *GetUserIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserIDResponse.Merge(m, src)
}
func (m *GetUserIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserIDResponse.Size(m)
}
func (m *GetUserIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserIDResponse proto.InternalMessageInfo

func (m *GetUserIDResponse) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

// GetUserFullNameRequest contains data required for get user full name request
type GetUserFullNameRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserFullNameRequest) Reset()         { *m = GetUserFullNameRequest{} }
func (m *GetUserFullNameRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserFullNameRequest) ProtoMessage()    {}
func (*GetUserFullNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b2fcb8862490326, []int{4}
}

func (m *GetUserFullNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserFullNameRequest.Unmarshal(m, b)
}
func (m *GetUserFullNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserFullNameRequest.Marshal(b, m, deterministic)
}
func (m *GetUserFullNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserFullNameRequest.Merge(m, src)
}
func (m *GetUserFullNameRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserFullNameRequest.Size(m)
}
func (m *GetUserFullNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserFullNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserFullNameRequest proto.InternalMessageInfo

func (m *GetUserFullNameRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

// GetUserFullNameResponse contains data required for get user full name response
type GetUserFullNameResponse struct {
	FullName             string   `protobuf:"bytes,1,opt,name=FullName,proto3" json:"FullName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserFullNameResponse) Reset()         { *m = GetUserFullNameResponse{} }
func (m *GetUserFullNameResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserFullNameResponse) ProtoMessage()    {}
func (*GetUserFullNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b2fcb8862490326, []int{5}
}

func (m *GetUserFullNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserFullNameResponse.Unmarshal(m, b)
}
func (m *GetUserFullNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserFullNameResponse.Marshal(b, m, deterministic)
}
func (m *GetUserFullNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserFullNameResponse.Merge(m, src)
}
func (m *GetUserFullNameResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserFullNameResponse.Size(m)
}
func (m *GetUserFullNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserFullNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserFullNameResponse proto.InternalMessageInfo

func (m *GetUserFullNameResponse) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthorizeUserRequest)(nil), "usergrpc.AuthorizeUserRequest")
	proto.RegisterType((*AuthorizeUserResponse)(nil), "usergrpc.AuthorizeUserResponse")
	proto.RegisterType((*GetUserIDRequest)(nil), "usergrpc.GetUserIDRequest")
	proto.RegisterType((*GetUserIDResponse)(nil), "usergrpc.GetUserIDResponse")
	proto.RegisterType((*GetUserFullNameRequest)(nil), "usergrpc.GetUserFullNameRequest")
	proto.RegisterType((*GetUserFullNameResponse)(nil), "usergrpc.GetUserFullNameResponse")
}

func init() { proto.RegisterFile("usergrpc.proto", fileDescriptor_9b2fcb8862490326) }

var fileDescriptor_9b2fcb8862490326 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x2d, 0x4e, 0x2d,
	0x4a, 0x2f, 0x2a, 0x48, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0xdc,
	0xb8, 0x44, 0x1c, 0x4b, 0x4b, 0x32, 0xf2, 0x8b, 0x32, 0xab, 0x52, 0x43, 0x8b, 0x53, 0x8b, 0x82,
	0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xf4, 0xb8, 0x84, 0x60, 0xe2, 0x89, 0x25, 0x99, 0xf9,
	0x79, 0x21, 0xf9, 0xd9, 0xa9, 0x79, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x58, 0x64, 0x94,
	0x8c, 0xb9, 0x44, 0xd1, 0xcc, 0x29, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x92, 0xe2, 0xe2, 0x00,
	0xf3, 0xf3, 0x73, 0x52, 0xc1, 0xda, 0x99, 0x83, 0xe0, 0x7c, 0x25, 0x27, 0x2e, 0x01, 0xf7, 0xd4,
	0x12, 0x10, 0xd7, 0xd3, 0x85, 0x5c, 0x8b, 0xb5, 0xb9, 0x04, 0x91, 0xcc, 0x80, 0x5a, 0x2a, 0xc6,
	0xc5, 0x06, 0x11, 0x81, 0x6a, 0x84, 0xf2, 0x94, 0x0c, 0xb8, 0xc4, 0xa0, 0x8a, 0xdd, 0x4a, 0x73,
	0x72, 0xfc, 0x12, 0x73, 0x53, 0x61, 0xd6, 0xe2, 0xd2, 0x61, 0xca, 0x25, 0x8e, 0xa1, 0x03, 0xe1,
	0x33, 0x98, 0x18, 0x54, 0x13, 0x9c, 0x6f, 0xd4, 0xc0, 0x04, 0xf1, 0xb6, 0x7b, 0x51, 0x41, 0xb2,
	0x50, 0x10, 0x17, 0x2f, 0x4a, 0xd8, 0x08, 0xc9, 0xe9, 0xc1, 0xe3, 0x03, 0x5b, 0xe0, 0x4b, 0xc9,
	0xe3, 0x94, 0x87, 0x58, 0xad, 0xc4, 0x20, 0xe4, 0xc6, 0xc5, 0x09, 0xf7, 0xb6, 0x90, 0x14, 0x42,
	0x3d, 0x7a, 0x78, 0x4a, 0x49, 0x63, 0x95, 0x83, 0x9b, 0x13, 0xc1, 0xc5, 0x8f, 0xe6, 0x3f, 0x21,
	0x05, 0x0c, 0x1d, 0x68, 0x81, 0x25, 0xa5, 0x88, 0x47, 0x05, 0xcc, 0x64, 0x27, 0x9e, 0x28, 0x2e,
	0x3d, 0x6b, 0x98, 0xba, 0x24, 0x36, 0x70, 0xc2, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc3,
	0x47, 0x56, 0xd7, 0x8a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserGrpcClient is the client API for UserGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserGrpcClient interface {
	// Authorize user
	AuthorizeUser(ctx context.Context, in *AuthorizeUserRequest, opts ...grpc.CallOption) (*AuthorizeUserResponse, error)
	// Get user ID
	GetUserID(ctx context.Context, in *GetUserIDRequest, opts ...grpc.CallOption) (*GetUserIDResponse, error)
	// Get user's full name
	GetUserFullName(ctx context.Context, in *GetUserFullNameRequest, opts ...grpc.CallOption) (*GetUserFullNameResponse, error)
}

type userGrpcClient struct {
	cc *grpc.ClientConn
}

func NewUserGrpcClient(cc *grpc.ClientConn) UserGrpcClient {
	return &userGrpcClient{cc}
}

func (c *userGrpcClient) AuthorizeUser(ctx context.Context, in *AuthorizeUserRequest, opts ...grpc.CallOption) (*AuthorizeUserResponse, error) {
	out := new(AuthorizeUserResponse)
	err := c.cc.Invoke(ctx, "/usergrpc.UserGrpc/AuthorizeUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGrpcClient) GetUserID(ctx context.Context, in *GetUserIDRequest, opts ...grpc.CallOption) (*GetUserIDResponse, error) {
	out := new(GetUserIDResponse)
	err := c.cc.Invoke(ctx, "/usergrpc.UserGrpc/GetUserID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGrpcClient) GetUserFullName(ctx context.Context, in *GetUserFullNameRequest, opts ...grpc.CallOption) (*GetUserFullNameResponse, error) {
	out := new(GetUserFullNameResponse)
	err := c.cc.Invoke(ctx, "/usergrpc.UserGrpc/GetUserFullName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserGrpcServer is the server API for UserGrpc service.
type UserGrpcServer interface {
	// Authorize user
	AuthorizeUser(context.Context, *AuthorizeUserRequest) (*AuthorizeUserResponse, error)
	// Get user ID
	GetUserID(context.Context, *GetUserIDRequest) (*GetUserIDResponse, error)
	// Get user's full name
	GetUserFullName(context.Context, *GetUserFullNameRequest) (*GetUserFullNameResponse, error)
}

// UnimplementedUserGrpcServer can be embedded to have forward compatible implementations.
type UnimplementedUserGrpcServer struct {
}

func (*UnimplementedUserGrpcServer) AuthorizeUser(ctx context.Context, req *AuthorizeUserRequest) (*AuthorizeUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthorizeUser not implemented")
}
func (*UnimplementedUserGrpcServer) GetUserID(ctx context.Context, req *GetUserIDRequest) (*GetUserIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserID not implemented")
}
func (*UnimplementedUserGrpcServer) GetUserFullName(ctx context.Context, req *GetUserFullNameRequest) (*GetUserFullNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserFullName not implemented")
}

func RegisterUserGrpcServer(s *grpc.Server, srv UserGrpcServer) {
	s.RegisterService(&_UserGrpc_serviceDesc, srv)
}

func _UserGrpc_AuthorizeUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGrpcServer).AuthorizeUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usergrpc.UserGrpc/AuthorizeUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGrpcServer).AuthorizeUser(ctx, req.(*AuthorizeUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserGrpc_GetUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGrpcServer).GetUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usergrpc.UserGrpc/GetUserID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGrpcServer).GetUserID(ctx, req.(*GetUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserGrpc_GetUserFullName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserFullNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGrpcServer).GetUserFullName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usergrpc.UserGrpc/GetUserFullName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGrpcServer).GetUserFullName(ctx, req.(*GetUserFullNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserGrpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "usergrpc.UserGrpc",
	HandlerType: (*UserGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthorizeUser",
			Handler:    _UserGrpc_AuthorizeUser_Handler,
		},
		{
			MethodName: "GetUserID",
			Handler:    _UserGrpc_GetUserID_Handler,
		},
		{
			MethodName: "GetUserFullName",
			Handler:    _UserGrpc_GetUserFullName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "usergrpc.proto",
}
